export const ErrorCodes = {
    VALIDATION_ERROR: "VALIDATION_ERROR",
    NOT_FOUND: "NOT_FOUND",
    INSUFFICIENT_INVENTORY: "INSUFFICIENT_INVENTORY",
    PAYMENT_FAILED: "PAYMENT_FAILED",
    INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;
